# Generated by Django 5.2.5 on 2025-08-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="username",
        ),
    ]
